#!/bin/sh

branch=""

getBranchFromFetch()
{
   lastLine=$(echo $1 | tail -n 1)
   branch=$(echo "$lastLine" | sed -n -e 's/^.*origin\///p')
}

compileAndUpload(){
   echo '\033[0;36mCompile and Upload\033[0m'
   arduino-cli compile /home/gian/IdeaProjects/Staff/Staff.ino
   arduino-cli upload /home/gian/IdeaProjects/Staff/Staff.ino
}

while true
do
   #date
   gitFetch=$(git fetch 2>&1)
   if [ -z "$gitFetch" ]; then
      echo "`date +%H:%M:%S`  Nothing yet."
       :
   else
      echo "\033[0;31m♥ Mmhhh I feel something ♥ I lalalalike it ;) ♥ \033[0m\n\
	      \033[0;36mGit Fetch:\033[0m\n\
	      $gitFetch"
      getBranchFromFetch "$gitFetch"
      echo "\033[0;36mGit Checkout\033[0m"
      git checkout "$branch"
      echo "\033[0;36mGit Pull\033[0m"
      git pull
      compileAndUpload
   fi
   
   gitFetch=""
   
   sleep 1
done
