#!/bin/sh

branch=""

getBranchFromFetch()
{
   lastLine=$(echo $1 | tail -n 1)
   branch=$(echo "$lastLine" | sed -n -e 's/^.*origin\///p')
}

compileAndUpload(){
   echo 'Compile and Upload'
   arduino-cli compile /home/gian/IdeaProjects/Staff/Staff.ino
   arduino-cli upload /home/gian/IdeaProjects/Staff/Staff.ino
}

while true
do
   #date
   gitFetch=$(git fetch 2>&1)
   if [ -z "$gitFetch" ]; then
#      echo "Nothing new"
       :
   else
      echo "Fetched:\n $gitFetch"
      getBranchFromFetch "$gitFetch"
      git checkout "$branch" && git pull && compileAndUpload
   fi
   
   gitFetch=""
   
   sleep 1
done
